export const recipeDepthRecovery = {
  "aloo-pakora": {
    whyItWorks: "Thin potato slices cook through in the same time that the gram-flour coating turns crisp. A thick batter clings to the potato and protects it from the oil, while steady frying heat cooks the spices without darkening the outside too quickly.",
    cues: ["Slice every potato to a similar thickness so none remain firm in the centre.", "The batter should coat the back of a spoon and leave no watery pool in the bowl.", "A finished pakora should be deep gold, crisp at the edge and tender when pierced."],
    substitutions: ["Rice flour can replace a small portion of the gram flour for a lighter crust.", "Reduce the chilli powder without reducing the cumin, turmeric or garam masala.", "A mandoline gives even slices, but use its guard and stop before reaching the end of the potato."],
    leftovers: "Pakoras are best straight from the fryer. Refrigerate leftovers for up to two days and reheat in a hot oven or air fryer until crisp and piping hot; microwaving makes the coating soft.",
  },
  "aloo-tikki": {
    whyItWorks: "Dry, floury potato binds the patties without making them heavy. Cooling the potato before shaping and using breadcrumbs sparingly keeps each tikki firm enough to turn while preserving a soft centre and crisp surface.",
    cues: ["Drain the potatoes thoroughly and let excess steam escape before mashing.", "The shaped patties should hold cleanly without sticking heavily to your hands.", "Turn only when the underside is properly golden and releases from the pan."],
    substitutions: ["Fine semolina can replace breadcrumbs when a wheat-free crumb is unsuitable only if dietary needs allow it.", "Amchur or lemon adds acidity; add lemon after cooking so the mixture does not become wet.", "Use less green chilli for a mild tikki while keeping the cumin and coriander unchanged."],
    leftovers: "Keep cooked tikki refrigerated for up to three days. Reheat in a lightly oiled pan or hot oven; uncooked shaped patties can be chilled for one day before frying.",
  },
  "bhindi-bhaji": {
    whyItWorks: "Okra stays distinct when it is completely dry and cooked in a broad, uncovered pan. Salt and acidic ingredients are added after the surface has started to brown, limiting the moisture that can make bhindi sticky or soft.",
    cues: ["Dry the washed okra thoroughly before trimming and slicing it.", "Give the pieces room to touch the hot pan rather than piling them into a small saucepan.", "The bhindi is ready when the cut edges are browned and the surface no longer looks wet."],
    substitutions: ["Amchur gives a dry tang; use a little lemon only after the pan leaves the heat.", "Kashmiri chilli supplies colour with moderate heat, while paprika is the mildest alternative.", "Coconut milk makes a softer, saucier version and should be simmered gently."],
    leftovers: "Refrigerate for up to two days and reheat uncovered in a frying pan. Avoid adding water, which softens the okra and brings back a sticky texture.",
  },
  "chapati-recipe": {
    whyItWorks: "Atta absorbs water gradually, so a short rest makes the dough easier to knead and roll without adding excess flour. A hot dry pan sets the first side quickly, then direct heat or firm pan contact encourages the steam pocket that makes a chapati puff.",
    cues: ["The rested dough should feel soft and smooth but should not coat your fingers.", "Roll from the centre and rotate often to keep an even circle and thickness.", "Small bubbles should appear before the first turn; scattered brown spots follow on the second side."],
    substitutions: ["Fine wholemeal bread flour works if atta is unavailable, although the bread may be slightly denser.", "Oil is optional in everyday chapati dough but helps the breads remain soft for longer.", "Use only enough dusting flour to prevent sticking because excess flour burns on the pan."],
    leftovers: "Stack cooked chapatis under a clean towel so trapped steam keeps them soft. Refrigerate for two days or freeze between sheets of baking paper, then reheat briefly in a hot dry pan.",
  },
  "coconut-dal-with-kidney-beans": {
    whyItWorks: "Tinned lentils and kidney beans make this a quick pantry dal, but the onion and tomato still need time to reduce before the coconut milk is added. A final uncovered simmer brings the beans and sauce together instead of leaving separate watery layers.",
    cues: ["Cook the onion until soft and lightly golden before adding the curry powder.", "The tomato should lose its raw smell and look thicker before the coconut milk goes in.", "The finished dal should coat a spoon while the beans remain intact."],
    substitutions: ["Any cooked brown or green lentil can replace the tinned brown lentils.", "Black beans work in place of kidney beans but give a slightly earthier flavour.", "Use light coconut milk for a looser dal and simmer longer if needed."],
    leftovers: "Refrigerate for up to three days or freeze for up to three months. Reheat gently with a splash of water and check the salt after the sauce loosens.",
  },
  "creamy-tofu-curry-with-homemade-roti": {
    whyItWorks: "Cornflour gives tofu a dry coating that browns before it enters the sauce. Reducing passata and creamed coconut separately prevents a thin curry, while resting the simple roti dough lets it roll without springing back.",
    cues: ["Pat the tofu dry before coating so the cornflour does not turn pasty.", "The curry sauce should look glossy and coat the tofu rather than run from it.", "Roti are ready to turn when bubbles appear and the underside has scattered brown marks."],
    substitutions: ["Extra-firm tofu gives the cleanest cubes; pressed firm tofu also works.", "Use a curry paste whose label confirms it is vegan and adjust salt around the paste.", "Plain flour makes softer roti while wholemeal flour gives more flavour and structure."],
    leftovers: "Keep curry refrigerated for up to three days and roti wrapped separately for two days. Reheat the sauce gently and warm roti in a dry pan so they do not become soggy.",
  },
  "dhal-with-caraway-aubergine": {
    whyItWorks: "Red lentils collapse into a creamy base while the aubergine is cooked separately so its browned edges are not lost in the dal. Caraway has a strong, warm aroma, so blooming it briefly in oil is enough to flavour the aubergine without overwhelming the lentils.",
    cues: ["Cut the aubergine evenly and leave space in the pan so the pieces brown rather than steam.", "The lentils are ready when no hard centre remains and the dal falls slowly from a spoon.", "Add lemon only after cooking so its brightness remains distinct."],
    substitutions: ["Cumin seed is a gentler alternative if caraway is unavailable.", "Yellow split lentils work but need a longer simmer than red lentils.", "Use water plus extra seasoning if your vegetable stock is strongly flavoured."],
    leftovers: "Refrigerate for up to three days, keeping any aubergine garnish separately when possible. Loosen the dal with water while reheating and add the aubergine near the end.",
  },
  "easy-vegan-indian-butter-chickpeas": {
    whyItWorks: "Peanut butter and coconut milk give this dairy-free sauce body, while tomato and tamari provide acidity and savoury depth. Adding chickpeas after the base has reduced gives them time to take on the seasoning without turning soft.",
    cues: ["Cook the onion until fully soft before adding garlic and ginger.", "Whisk the peanut butter into warm liquid so no dense lumps remain.", "Simmer gently after coconut milk is added; a hard boil can make the sauce look oily."],
    substitutions: ["Smooth cashew butter can replace peanut butter for a milder sauce where allergies allow.", "Soy sauce can replace tamari unless a gluten-free dish is required.", "Use either soy curls or potato according to the version you want, adjusting liquid so the sauce stays thick."],
    leftovers: "Refrigerate for up to three days or freeze for two months. Reheat slowly with a small splash of water because the chickpeas and soy curls continue to absorb sauce.",
  },
  "easy-vegan-south-indian-rava-upma-recipe": {
    whyItWorks: "Dry-roasted semolina absorbs seasoned water without becoming pasty. The tempering flavours the oil first, and adding rava in a steady stream while stirring prevents clumps and gives upma its soft, separate texture.",
    cues: ["Roasted rava should smell nutty but remain pale rather than brown.", "Mustard seeds should pop before the curry leaves and dal are added.", "The finished upma should be moist and fluffy, with no dry grains or pooled water."],
    substitutions: ["Use coarse or medium rava; very fine semolina produces a softer result.", "Cashews can be added to the tempering for crunch but are not required.", "Frozen peas or finely diced carrot may be cooked with the onion for a vegetable version."],
    leftovers: "Upma is best fresh but keeps refrigerated for two days. Reheat covered with a spoonful of water, fluffing gently once the steam has softened it.",
  },
  "homemade-cilantro-chutney": {
    whyItWorks: "Tender coriander stems carry plenty of flavour and give the chutney body, while mint, citrus and green chilli keep it bright. Blending with only enough yogurt to move the blades avoids a thin chutney that runs off snacks and breads.",
    cues: ["Wash the herbs thoroughly and shake away excess water before blending.", "Stop and scrape the blender rather than adding too much liquid at once.", "Taste for salt and citrus after blending because herb bunches vary in size and strength."],
    substitutions: ["Use all coriander when mint is unavailable, adding a little extra citrus to taste.", "Unsweetened soy or coconut yogurt works; avoid sweetened or vanilla varieties.", "Remove chilli seeds or reduce the number of chillies for a milder chutney."],
    leftovers: "Refrigerate immediately in a clean sealed jar and use within two days. The colour darkens with air exposure, so press reusable wrap to the surface or use a small container.",
  },
  "indian-pancakes-with-spiced-potato-filling": {
    whyItWorks: "Gram flour brings savoury flavour while plain flour gives the pancakes enough flexibility to fold around the filling. Cooking the spiced potato until dry prevents steam and moisture from making the pancakes soggy.",
    cues: ["The batter should pour in a ribbon and spread easily across the pan.", "Turn a pancake when the surface loses its wet shine and the edge lifts cleanly.", "The potato filling should mound on a spoon without leaving liquid behind."],
    substitutions: ["Use all gram flour for a more fragile gluten-free-style pancake only with careful handling.", "Peas can be folded into the potato filling for sweetness and colour.", "Amchur can replace some lemon juice when a drier filling is preferred."],
    leftovers: "Store pancakes and filling separately for up to two days. Reheat pancakes briefly in a dry pan and warm the potato thoroughly before filling and serving.",
  },
  "indian-style-cauliflower": {
    whyItWorks: "High heat browns the exposed edges of cauliflower before the centre becomes soft. Coating the florets evenly and leaving space on the tray lets moisture escape, while ginger, lime zest and coriander are added with care so their fresher aromas remain clear.",
    cues: ["Dry the florets after washing so the seasoned oil adheres.", "Use one uncrowded layer and turn only after the underside has begun to colour.", "The stem should accept a small knife while the edges remain browned and slightly crisp."],
    substitutions: ["Broccoli roasts more quickly and should be checked several minutes earlier.", "Kashmiri chilli can replace part of the curry powder for colour and gentle heat.", "Lemon zest works in place of lime and should be added after roasting."],
    leftovers: "Refrigerate for up to three days. Reheat uncovered in a hot oven or air fryer; a microwave softens the browned edges.",
  },
  "instant-rava-idli-a-south-indian-breakfast-recipe": {
    whyItWorks: "Semolina and rice flour create a tender steamed crumb without fermentation. Yogurt supplies acidity and baking soda is added just before steaming, so the batter must go into a fully heated steamer while that reaction is active.",
    cues: ["The rested batter should fall from a spoon but not pour like milk.", "Grease the moulds lightly and fill them only far enough to allow a little rise.", "A skewer should leave the centre clean before the idli are rested and unmoulded."],
    substitutions: ["Use an unsweetened plant yogurt with some acidity, such as soy yogurt.", "Plant milk is added only as needed because different yogurts vary in thickness.", "Finely grated carrot can be added without making the batter overly wet."],
    leftovers: "Cool promptly and refrigerate for up to two days. Re-steam briefly or microwave covered with a few drops of water so the idli soften without drying out.",
  },
  "jalebi-recipe-traditional-method": {
    whyItWorks: "Fermentation gives traditional jalebi a light interior and slight tang, while a one-string syrup is thin enough to soak the fried coils without making them limp. Moderate frying heat allows the rings to set before their colour deepens.",
    cues: ["The fermented batter should show small bubbles and fall in an unbroken ribbon.", "A piped coil should hold its shape on contact with the oil rather than spreading flat.", "Warm jalebi need only a brief syrup soak; they should remain crisp when lifted."],
    substitutions: ["A tiny pinch of turmeric provides colour without artificial dye; too much affects flavour.", "A piping bag with a very small cut corner works if no squeeze bottle is available.", "Cardamom can accompany saffron in the syrup, but use it lightly."],
    leftovers: "Jalebi are best on the day they are fried. Keep at cool room temperature for one day in a loosely covered container; refrigeration and sealed containers soften the crust.",
  },
  "kachumber-easy-10-minute-indian-salad": {
    whyItWorks: "Kachumber relies on contrast rather than a heavy dressing: crisp cucumber and onion, juicy tomato, roasted cumin and fresh lemon. Salting immediately before serving keeps the vegetables from releasing enough water to dilute the seasoning.",
    cues: ["Cut the vegetables to a similar small size so each spoonful is balanced.", "Remove watery tomato cores if the salad will stand for more than a few minutes.", "Taste after adding lemon because tomato acidity changes from batch to batch."],
    substitutions: ["Use lime instead of lemon for a slightly sharper finish.", "A mild red onion or shallot can replace standard red onion.", "Leave out green chilli for a mild salad while keeping the roasted cumin and coriander."],
    leftovers: "Kachumber is best mixed just before eating. Refrigerate leftovers for no more than one day; drain released liquid and refresh with lemon and coriander before serving.",
  },
  "masala-french-toast-savory-bombay-toast": {
    whyItWorks: "Chickpea flour binds the savoury coating without egg and sets into a crisp, seasoned surface. Brief soaking is enough: the bread should absorb flavour at the outside while retaining enough structure to turn in the pan.",
    cues: ["Whisk the batter smooth before adding onion and coriander.", "Dip each side quickly rather than leaving bread submerged until soft.", "Turn when the underside is golden and the coating releases cleanly from the pan."],
    substitutions: ["Firm day-old bread handles the batter better than very soft fresh slices.", "Finely chopped tomato can be added only after removing its wet seeds.", "Reduce chilli independently while retaining turmeric, coriander and salt."],
    leftovers: "This is best eaten immediately. If needed, refrigerate for one day and reheat in a dry frying pan or hot oven until the edges become crisp again.",
  },
  "masala-oats-recipe-healthy-weight-loss-masala-oats-upma": {
    whyItWorks: "The masala and vegetables are cooked before the oats so the finished bowl tastes seasoned rather than merely stirred together. Adding rolled oats only after the liquid boils helps them thicken evenly while retaining some texture.",
    cues: ["Cook the onion and vegetables until nearly tender before adding water.", "The liquid should be actively boiling when the oats are stirred in.", "Stop cooking while the mixture is slightly looser than desired because oats continue to absorb liquid."],
    substitutions: ["Use ordinary rolled oats rather than instant oats for a less pasty texture.", "Choose quick-cooking vegetables and dice them evenly.", "Neutral oil works in place of vegan ghee without changing the structure."],
    leftovers: "Refrigerate for up to two days. Reheat over low heat with a little water, stirring gently, then restore the fresh flavour with lemon and coriander.",
  },
  "mushroom-matar-masala-mushroom-pea-curry": {
    whyItWorks: "Mushrooms are cooked until their released moisture evaporates before peas and chickpeas finish in the masala. This keeps the sauce concentrated and allows the savoury mushroom flavour to remain distinct from the tomato and spices.",
    cues: ["Use a wide pan so the mushrooms sizzle instead of boiling in their own liquid.", "The tomato base should be darker, thick and no longer smell raw.", "Add peas late enough that they stay green and retain a little bite."],
    substitutions: ["Chestnut, cremini or white mushrooms all work; slice them to an even thickness.", "Frozen peas can go straight into the simmering sauce.", "Leave out spinach or add it only at the end so it does not release excess water."],
    leftovers: "Refrigerate for up to two days and reheat until piping hot. Use only a small splash of water because mushrooms release more moisture as they warm.",
  },
  "peanut-and-coconut-balls": {
    whyItWorks: "Dates bind the ground peanuts, coconut and seeds without a cooked sugar syrup. Processing the dry ingredients first gives an even texture, while adding warm water little by little prevents a mixture that is too soft to roll.",
    cues: ["Stop grinding peanuts before they release enough oil to become peanut butter.", "A squeezed spoonful should hold together without feeling wet or sticky.", "Roll firmly between your palms and chill if the mixture softens in a warm kitchen."],
    substitutions: ["Use soft pitted dates; soak very firm dates briefly and drain them thoroughly.", "Sesame seeds can replace some chia where appropriate, though the flavour changes.", "Keep the coconut unsweetened so the date sweetness remains balanced."],
    leftovers: "Store refrigerated in an airtight container for up to one week. Let the balls stand for a few minutes before eating if you prefer a softer texture.",
  },
  "poori": {
    whyItWorks: "A firm whole-wheat dough traps steam when a thin disc enters hot oil, causing the poori to balloon. Even rolling and sufficient oil depth matter more than extra ingredients; pressing gently with a slotted spoon helps the top meet the hot oil and puff.",
    cues: ["The dough should be firmer than chapati dough and should not feel sticky.", "Roll each disc evenly with no thin edge that can leak steam.", "The oil is ready when a small dough scrap rises steadily without blackening."],
    substitutions: ["Atta gives the most supple whole-wheat dough, though fine wholemeal flour can work.", "Use neutral high-heat oil and never fill the pan more than halfway.", "Do not add excessive dusting flour because loose flour burns in the frying oil."],
    leftovers: "Poori are best eaten immediately. Refrigerate for up to two days and reheat in a hot oven, accepting that reheated breads will not puff as crisply as fresh ones.",
  },
  "pressure-cooker-indian-moong-dal": {
    whyItWorks: "Whole moong needs pressure to become tender while retaining some shape. Deglazing before sealing prevents scorching, and finishing with garam masala, lemon and coriander after pressure cooking preserves aromas that would otherwise flatten during the long cook.",
    cues: ["Rinse the moong until the water is much clearer before it enters the cooker.", "Scrape the cooker base clean after sautéing the onion and tomato.", "Cooked beans should yield easily when pressed but should not all dissolve."],
    substitutions: ["Soaked whole moong cooks more evenly and may need a shorter pressure time.", "Brown lentils work with adjusted timing but will not have the same texture.", "Add more cayenne at the end rather than guessing before pressure cooking."],
    leftovers: "The dal thickens considerably as it cools. Refrigerate for three days, loosen with water while reheating and bring it to a thorough simmer before serving.",
  },
  "quick-punjabi-breakfast-chole": {
    whyItWorks: "Tea gives Punjabi-style chole a deep colour without making the gravy taste sweet, while a final hot tempering restores vivid spice aroma. Simmering the chickpeas in the reduced tomato masala helps them absorb seasoning rather than sitting in a separate sauce.",
    cues: ["Remove the tea bag once the chickpea liquid is dark enough; never split it into the pot.", "Cook the tomato masala until thick, darker and showing oil at the edge.", "Pour the tempering over the finished chole while it is still audibly sizzling."],
    substitutions: ["Cooked dried chickpeas give the firmest texture; tinned chickpeas are quicker.", "Amchur supplies the characteristic dry acidity, with lemon as a final alternative.", "Reduce the fresh and dried chilli independently while keeping the other spices."],
    leftovers: "Chole often improves overnight. Refrigerate for up to three days and reheat with enough water to loosen the gravy, adding a fresh squeeze of lemon if needed.",
  },
  "saag-butter-beans": {
    whyItWorks: "Butter beans bring a soft, creamy centre to a spinach gravy, but they are folded in only after the saag base has reduced. A separate garlic and chilli tempering at the finish supplies contrast without boiling away its aroma.",
    cues: ["Cook the onion until properly golden before adding tomato paste and spices.", "Thawed spinach should be squeezed if it releases a large amount of water.", "Fold in the beans gently so their skins remain intact."],
    substitutions: ["Cannellini beans are the closest easy substitute for butter beans.", "Cashew cream can replace plant yogurt for a richer finish.", "Use paprika instead of Kashmiri chilli when you want colour with very little heat."],
    leftovers: "Refrigerate for up to three days. Reheat gently with a spoonful of water and prepare a fresh small tempering if you want to restore the garlic aroma.",
  },
  "sambar": {
    whyItWorks: "Toor dal provides body while vegetables contribute sweetness and texture. Roasting and grinding the spice mixture separately gives a fresher sambar aroma, and the mustard-fenugreek tempering is added at the end so it remains distinct.",
    cues: ["The dal should mash easily before it is combined with the vegetables.", "Choose vegetables that are tender but still hold their shape.", "Mustard seeds should pop and curry leaves should crackle when the final tempering is ready."],
    substitutions: ["Red lentils cook more quickly than toor dal but give a softer, less traditional body.", "Use tamarind for characteristic sourness and adjust it against the natural sweetness of the vegetables.", "Vary the vegetables by season while keeping their pieces similar in cooking time."],
    leftovers: "Refrigerate for up to three days; the flavour deepens and the dal thickens. Add water while reheating and bring to a full simmer before serving with rice or idli.",
  },
  "sweet-potato-chickpea-curry-easy-vegan": {
    whyItWorks: "Roasting sweet potato first caramelises its edges and prevents it dissolving into the coconut sauce. Chickpeas then simmer in the onion-tomato masala, with the roasted cubes folded back near the end so the two textures remain distinct.",
    cues: ["Roast the sweet potato in one layer until browned outside and just tender inside.", "The onion and tomato base should be reduced before broth and coconut milk are added.", "Simmer gently after adding coconut milk so the sauce stays smooth."],
    substitutions: ["Butternut squash can replace sweet potato and may cook a little more quickly.", "Full-fat coconut milk produces a richer sauce; light coconut milk remains looser.", "Cooked dried chickpeas work in the same drained quantity as tinned."],
    leftovers: "Refrigerate for up to three days or freeze for two months. Reheat slowly with a splash of water and stir carefully so the sweet potato keeps its shape.",
  },
  "sweet-potato-chickpea-spinach-curry": {
    whyItWorks: "Sweet potato is simmered until nearly tender before coconut milk and spinach are added. That order prevents overcooked greens and keeps the coconut sauce fresh while giving chickpeas enough time to absorb the rogan josh-style masala.",
    cues: ["Cut the sweet potato into even cubes so they finish together.", "Add coconut milk only once the potato is almost tender.", "Fold spinach in at the end and stop cooking as soon as it has wilted."],
    substitutions: ["Butternut squash can replace the sweet potato.", "Use a vegan curry paste and check its salt and heat before adding extra seasoning.", "Frozen spinach works after thawing and squeezing out excess water."],
    leftovers: "Refrigerate for up to three days or freeze for up to two months. Reheat gently so the sweet potato remains intact, adding water only if the sauce has thickened heavily.",
  },
  "tarka-dal": {
    whyItWorks: "The lentils are cooked until creamy before the tarka is prepared separately. Pouring hot cumin, onion, chilli, ginger and garlic over the dal at the finish creates layers of aroma that would be lost if everything simmered together from the start.",
    cues: ["The lentils should collapse fully and have no chalky centre.", "Cook cumin until fragrant, not black, before adding the onion.", "The tarka is ready when the onion is golden and the garlic no longer smells raw."],
    substitutions: ["Red lentils give the quickest creamy base; yellow lentils need longer.", "Use fewer whole green chillies for less heat without reducing cumin or coriander.", "Add water gradually at the end to choose a spoonable or pourable consistency."],
    leftovers: "Keep refrigerated for up to three days. Dal thickens overnight, so loosen it while reheating and make a small fresh cumin tarka if serving to guests.",
  },
  "tofu-bhurji-indian-style-tofu-scramble": {
    whyItWorks: "Pressed tofu is crumbled into pieces of different sizes so the bhurji feels substantial rather than pasty. The onion, pepper and tomato are cooked before the tofu, preventing watery vegetables from diluting the ground spices.",
    cues: ["Press tofu well and crumble it by hand instead of blending it.", "Cook the tomato until most visible moisture has evaporated.", "The finished bhurji should be moist but leave no liquid in the pan."],
    substitutions: ["Extra-firm tofu needs less pressing than ordinary firm tofu.", "Leave out bell pepper or replace it with finely chopped peas.", "Black salt can add an egg-like aroma, but use it lightly and reduce ordinary salt."],
    leftovers: "Refrigerate for up to three days and reheat in a frying pan until piping hot. Add lemon and coriander after reheating to restore freshness.",
  },
  "vegan-chicken-madras": {
    whyItWorks: "Browning the seitan separately gives it crisp edges that survive the sauce. The onion and tomato purée form a concentrated masala before water is added, and the seitan returns only for the final simmer so it absorbs flavour without becoming overly soft.",
    cues: ["Toast the whole spices until fragrant but remove any split cardamom husks before serving.", "Cook the onion until properly golden and the tomato purée until brick red.", "The finished sauce should cling to the seitan instead of pooling thinly around it."],
    substitutions: ["Use another vegan chicken-style product and adjust simmering time to its texture.", "Firm tofu works but should be pressed and browned first.", "Control heat with the chilli quantity while retaining the measured Madras curry powder for character."],
    leftovers: "Refrigerate for up to three days and reheat gently until piping hot. Add a small splash of water because seitan absorbs sauce as it rests.",
  },
  "vegan-chickpea-masala-omelette": {
    whyItWorks: "Besan sets into a savoury pancake when the water ratio and pan heat are balanced. Finely chopped vegetables cook inside the batter, while ajwain and coriander season it without relying on an egg substitute.",
    cues: ["Rest the batter briefly so the gram flour hydrates and small lumps soften.", "Chop vegetables finely and remove wet tomato seeds.", "Turn when the top looks nearly set and the edges release cleanly from the pan."],
    substitutions: ["Use plain water for the cleanest flavour; unsweetened plant milk gives a softer result.", "Spring onion can replace red onion for a milder filling.", "Leave out chilli while retaining ajwain, turmeric and ground coriander."],
    leftovers: "Cooked omelettes keep refrigerated for up to two days. Reheat in a lightly oiled pan until hot on both sides; the batter itself is best cooked on the day it is mixed.",
  },
  "vegan-roti-chapati": {
    whyItWorks: "Roti needs only atta, salt and water, so texture depends on hydration, kneading and pan heat rather than a long ingredient list. Resting lets the flour absorb water evenly and makes thin rounds easier to roll without tearing.",
    cues: ["The dough should be soft, smooth and no longer sticky after resting.", "Roll evenly from the centre and avoid a thin rim that will become brittle.", "Flip when small bubbles form, then press lightly to encourage the roti to puff."],
    substitutions: ["Fine wholemeal flour can replace atta but may require slightly more water.", "Warm water speeds hydration, though it should not be hot enough to cook the flour.", "Use minimal dusting flour because loose flour scorches on the pan."],
    leftovers: "Stack hot roti beneath a clean towel. Refrigerate for two days or freeze between sheets of baking paper, then warm briefly on a dry pan.",
  },
  "vegetable-balti": {
    whyItWorks: "A balti-style sauce is cooked quickly and boldly, but dense vegetables still need a head start. Adding cauliflower and squash before courgette, peppers and peas keeps every vegetable recognisable while the spice paste reduces into a thick coating.",
    cues: ["Cook the onion-spice paste until the raw garlic and ginger aroma has gone.", "Cut dense vegetables smaller than quick-cooking courgette and pepper.", "The sauce should coat the vegetables while they remain intact, not collapse into a stew."],
    substitutions: ["Use seasonal vegetables with similar cooking times and avoid overcrowding the pan.", "Reduce the number of chillies substantially for a milder version while keeping the ground spices.", "Serve with separately cooked rice if you prefer tighter control over each texture."],
    leftovers: "Refrigerate curry for up to three days. Cool cooked rice rapidly, refrigerate within one hour and use within one day; reheat rice only once until steaming hot.",
  },
  "vegetable-upma-indian-savory-breakfast": {
    whyItWorks: "Roasting semolina keeps the grains separate and develops a gentle nutty aroma. The mustard-seed and dal tempering seasons the cooking water first, and adding rava slowly while stirring prevents lumps.",
    cues: ["Dry-roasted semolina should smell nutty but remain pale.", "Mustard seeds need to pop and the dals should turn golden before water is added.", "The finished upma should be soft and fluffy with no dry centre in the grains."],
    substitutions: ["Use medium semolina for a clear grain; very fine semolina gives a softer texture.", "Choose small, quick-cooking vegetables and keep the total quantity modest.", "Neutral oil works in place of vegan ghee."],
    leftovers: "Refrigerate for up to two days. Sprinkle with water and reheat covered over low heat, then fluff and finish with fresh lime or lemon.",
  },
};
