export type RecipeDepth = {
  whyItWorks: string;
  cues: string[];
  substitutions: string[];
  leftovers: string;
  instructions?: string[];
};

export const recipeDepth: Record<string, RecipeDepth> = {
  "chana-masala": {
    whyItWorks: "Chana masala tastes fullest when the onion and tomato are cooked into a concentrated base before the chickpeas go in. Crushing a few chickpeas releases starch, thickening the sauce without flour or cream, while lemon added at the end restores brightness lost during simmering.",
    cues: ["The onion should be deep gold rather than merely translucent.", "The tomato masala is ready when it looks darker, glossy and no longer smells raw.", "The finished sauce should cling to the chickpeas instead of pooling beneath them."],
    substitutions: ["Use cooked dried chickpeas in place of tins; allow roughly 480 g drained weight.", "Amchur can replace lemon juice for a drier, fruitier acidity.", "Reduce the chilli rather than the garam masala if you want a milder curry."],
    leftovers: "Cool promptly and refrigerate for up to three days. Reheat with a splash of water because the chickpeas continue to absorb sauce overnight.",
    instructions: [
      "Heat the oil in a wide pan over medium heat. Add the finely chopped onion and cook for 8 to 10 minutes, stirring regularly, until soft and deep golden.",
      "Add the minced garlic and grated ginger. Cook for 30 to 45 seconds, until fragrant and no longer raw-smelling.",
      "Stir in the ground cumin, ground coriander, turmeric, chilli powder and half of the garam masala. Cook for 20 seconds, stirring constantly so the spices do not catch.",
      "Add the chopped tomatoes and cook for 8 to 10 minutes, until darker, glossy and reduced to a thick masala.",
      "Add the drained chickpeas, salt and 120 ml water. Crush a small spoonful of chickpeas against the side of the pan, then simmer gently for 10 to 12 minutes.",
      "When the sauce coats the chickpeas, stir in the remaining garam masala, lemon juice and most of the coriander. Taste and adjust the salt or chilli.",
      "Garnish with the remaining coriander and serve hot with basmati rice, roti or naan.",
    ],
  },
  "bombay-aloo": {
    whyItWorks: "Parboiling the potatoes gives a fluffy centre, while finishing them in a wide pan creates dry, spice-coated edges. Mustard and cumin are started in oil so their flavour reaches every cube; lemon and coriander are held back until the end so they remain fresh.",
    cues: ["A knife should enter the potato with slight resistance after parboiling.", "Mustard seeds should begin popping before the cumin is added.", "Turn the potatoes gently and let one side colour before moving them again."],
    substitutions: ["Waxy potatoes hold neat cubes; floury potatoes give rougher, crispier edges.", "Use lime instead of lemon, or a small pinch of amchur.", "For less heat, halve the chilli powder but keep the other spices unchanged."],
    leftovers: "Refrigerate for up to three days and reheat in a frying pan or hot oven; a microwave softens the browned edges.",
    instructions: [
      "Boil the potatoes in salted water until a knife enters with slight resistance. Drain, cool briefly, then peel if preferred and cut into even cubes.",
      "Heat the oil in a wide frying pan. Add the mustard seeds and cover loosely until they begin to pop, then add the cumin seeds.",
      "Add the potatoes and leave them undisturbed for 2 minutes so one side begins to colour.",
      "Sprinkle over the turmeric, chilli powder, ground coriander, garam masala and salt. Turn gently until every cube is evenly coated.",
      "Cook uncovered for 5 to 7 minutes, turning only occasionally, until the edges are golden and the spices smell toasted rather than raw.",
      "Remove from the heat, add the lemon juice and fresh coriander, and taste for salt before serving.",
    ],
  },
  "indian-red-lentil-dahl": {
    whyItWorks: "Red lentils naturally collapse as they cook, producing a creamy dal without blending. Adding coconut milk after the lentils begin to soften preserves its richness, and final acidity prevents the finished bowl from tasting flat or overly sweet.",
    cues: ["Rinse until the water is much less cloudy to remove loose surface starch.", "Keep the simmer gentle so the base does not catch as it thickens.", "The lentils are ready when no hard centre remains and the dal falls slowly from a spoon."],
    substitutions: ["Use water plus a little extra salt if vegetable stock is unavailable.", "Light coconut milk gives a looser result; simmer a few minutes longer if needed.", "Lime juice works in place of lemon."],
    leftovers: "Dal thickens substantially in the fridge. Keep for up to three days and loosen with water while reheating, then check the salt and lemon again.",
    instructions: [
      "Rinse the red lentils under cold water until the water is much less cloudy, then drain.",
      "Heat the coconut oil in a saucepan. Add the onion and cook over medium heat until soft and lightly golden.",
      "Add the garlic and ginger and cook for 45 seconds. Stir in the turmeric, paprika, garam masala and cumin for a further 20 seconds.",
      "Add the chopped tomatoes and cook until softened and no longer raw-smelling.",
      "Stir in the lentils and vegetable stock. Bring to a gentle simmer and cook for 12 to 15 minutes, stirring more frequently as the mixture thickens.",
      "Add the coconut milk and continue simmering until the lentils have completely softened and the dal is creamy. Add water if it becomes too thick.",
      "Season with salt, optional coconut sugar and lemon juice. Garnish with fresh coriander and serve hot.",
    ],
  },
  "tofu-butter-masala-recipe": {
    whyItWorks: "Browning tofu separately gives it a firmer surface that survives the sauce. The tomato base needs enough cooking to lose its raw sharpness before cashew or plant cream is added; garam masala belongs near the finish so its aroma stays distinct.",
    cues: ["Pat tofu dry so it browns rather than steams.", "Cook the tomato until it darkens and the oil begins to show at the edges.", "After adding the creamy element, simmer gently rather than boiling hard."],
    substitutions: ["Extra-firm tofu gives the cleanest cubes; pressed firm tofu also works.", "Blended soaked cashews or oat cream can replace vegan cream.", "Kasuri methi is distinctive; if omitted, do not replace it with fresh fenugreek in equal quantity."],
    leftovers: "Refrigerate for up to three days. Reheat slowly with a spoonful of water to protect the creamy sauce from splitting.",
    instructions: [
      "Pat the tofu dry, cut into cubes and brown in a lightly oiled frying pan. Transfer to a plate.",
      "In the same pan, cook the onion with the cardamom, ginger and garlic until soft and golden.",
      "Add the tomatoes, cashews and salt. Cook until the tomatoes collapse and the mixture becomes thick and glossy.",
      "Stir in the chilli powder and ground coriander, cook briefly, then blend the mixture with enough water to make a completely smooth sauce.",
      "Melt the vegan butter in the pan. Add the bay leaf, cinnamon and cloves, if using, and cook until fragrant.",
      "Pour in the blended sauce and simmer gently until it coats the back of a spoon.",
      "Add the browned tofu and simmer for 3 to 4 minutes. Stir in the sugar, crushed kasuri methi, garam masala and plant cream.",
      "Warm through without boiling hard, taste for salt and garnish with fresh coriander.",
    ],
  },
  "saag-aloo": {
    whyItWorks: "Potatoes need a head start before the greens are added. Cooking spinach only until tender keeps its colour and prevents a muddy flavour, while a final uncovered simmer lets excess water evaporate and leaves the masala coating the potatoes.",
    cues: ["The potatoes should be almost tender before the spinach enters the pan.", "Add greens in batches and let each batch wilt before adding more.", "The finished dish should be moist but should not leave watery liquid on the plate."],
    substitutions: ["Use half spinach and half mustard greens for a more assertive flavour.", "Frozen spinach works after thawing and squeezing out excess water.", "Small waxy potatoes keep their shape better than very floury varieties."],
    leftovers: "Keep refrigerated for up to three days and reheat covered over low heat. Add only a teaspoon or two of water if it appears dry.",
    instructions: [
      "Heat the oil in a wide pan. Add the cumin seeds and cook until fragrant.",
      "Add the onion and cook until golden. Stir in the ginger and garlic and cook for 1 minute.",
      "Add the tomato, ground coriander, garam masala, turmeric and chilli powder. Cook until the tomato is soft and the masala looks thick.",
      "Add the diced potatoes and turn to coat. Pour in the water, cover and simmer until the potatoes are almost tender.",
      "Add the spinach in batches, allowing each batch to wilt before adding the next.",
      "Season with salt and cook uncovered until the potatoes are tender and excess spinach liquid has evaporated.",
    ],
  },
  "veg-biryani-vegetable-biryani-recipe": {
    whyItWorks: "Biryani depends on separate rice grains and controlled moisture. Part-cooking the rice before layering prevents it turning soft, while resting the sealed pot allows trapped steam to finish the centre without vigorous stirring.",
    cues: ["Soaked basmati should be boiled only until a grain bends but still has a firm centre.", "The vegetable masala should be thick, not watery, before layering.", "Rest the cooked biryani before lifting gently from the side with a broad spoon."],
    substitutions: ["Choose vegetables that hold their shape, such as cauliflower, carrot, beans and peas.", "Use turmeric-tinted warm plant milk if saffron is unavailable.", "Mint and coriander have different roles; use both where possible rather than doubling one."],
    leftovers: "Cool rice quickly, refrigerate within one hour and eat within one day. Reheat once until steaming hot throughout, adding a few drops of water before covering.",
  },
  "samosa-recipe": {
    whyItWorks: "A firm, low-moisture dough produces a blistered, crisp shell. The potato filling must cool completely before shaping, and frying from moderately warm oil gives the pastry time to cook through before the outside becomes dark.",
    cues: ["The dough should feel firmer than chapati dough and should not spring back quickly.", "The filling must be dry enough to mound without leaking liquid.", "Small bubbles should rise steadily around a pastry scrap; violent bubbling means the oil is too hot."],
    substitutions: ["Frozen peas are ideal and need no thawing before the filling cooks.", "Amchur may be replaced with lemon added after the filling leaves the heat.", "For baking, brush generously with oil, although the crust will be less blistered."],
    leftovers: "Refrigerate for up to two days and reheat in an oven or air fryer until piping hot. Avoid microwaving if you want to retain the crisp shell.",
    instructions: [
      "Combine the flour, ajwain and salt. Rub in the cold vegan butter until the mixture resembles coarse crumbs.",
      "Add water a little at a time and knead into a firm, smooth dough. Cover and rest for 30 minutes.",
      "For the filling, heat a little oil and cook the green chilli and ginger for 30 seconds. Add the cumin, ground coriander, fennel, turmeric and amchur.",
      "Add the boiled potatoes and peas, season with salt and cook for 3 to 5 minutes. Mash lightly, leaving some texture, then cool completely.",
      "Divide the dough into seven balls. Roll each into a thin oval and cut across the middle to make two semicircles.",
      "Moisten the straight edge of one semicircle, form it into a cone and press the seam firmly. Fill with two teaspoons of cooled filling.",
      "Moisten and seal the open edge, pressing out trapped air. Repeat with the remaining pastry and filling.",
      "Heat enough neutral or peanut oil for deep-frying to about 165°C. Fry in small batches, turning occasionally, until evenly golden and crisp.",
      "Drain on kitchen paper and serve hot.",
    ],
  },
  "onion-bhaji": {
    whyItWorks: "Salt draws moisture from sliced onion, and that moisture hydrates the gram flour. Starting with very little added water prevents a cakey batter, leaving irregular onion strands exposed so they become crisp in the oil.",
    cues: ["Slice onions evenly so thin strands cook before thicker pieces burn.", "The mixture should cling when squeezed but should not pour like pancake batter.", "Fry in small batches so the oil temperature recovers quickly."],
    substitutions: ["Chickpea flour and gram flour can be used interchangeably here.", "A spoonful of rice flour makes the edges lighter and crisper.", "Fresh green chilli can be omitted without altering the structure."],
    leftovers: "Bhajis are best fresh. Refrigerate for up to two days and revive in a hot oven or air fryer; do not re-fry already cooked bhajis.",
    instructions: [
      "Peel the onions, halve them from root to tip and slice thinly and evenly.",
      "Combine the onion with the gram flour, rice flour, baking powder, turmeric, cayenne, cumin, ground coriander and salt.",
      "Squeeze and toss the mixture with clean hands. Let it stand for 10 minutes so the salted onion releases moisture.",
      "Mix again, adding water one tablespoon at a time only until the flour clings thickly to the onion strands.",
      "Heat deep-frying oil to about 175°C. Carefully lower loose tablespoon-sized portions into the oil without compacting them.",
      "Fry in small batches, turning once, until crisp and deep golden throughout.",
      "Drain on kitchen paper, season lightly and serve immediately.",
    ],
  },
  "vegan-garlic-naan": {
    whyItWorks: "A soft, hydrated dough and a properly heated pan create the characteristic bubbles. Resting relaxes the gluten so the dough stretches without shrinking, while garlic butter is applied after cooking to avoid scorching the garlic.",
    cues: ["The dough should be soft and slightly tacky, not dry or heavily floured.", "The pan is ready when a drop of water evaporates almost immediately.", "Flip when large bubbles form and the underside has scattered dark spots."],
    substitutions: ["Unsweetened soy yogurt gives dependable tenderness; thick oat yogurt also works.", "Use melted vegan butter or neutral oil for the finish.", "Nigella seeds are optional but add a savoury onion-like aroma."],
    leftovers: "Cool completely, wrap and refrigerate for two days or freeze between sheets of baking paper. Reheat briefly in a hot dry pan, then brush again.",
    instructions: [
      "Melt the vegan butter, stir in the minced garlic and set aside so the flavour infuses.",
      "Combine the flour, salt, sugar and baking powder in a large bowl.",
      "Add the soy yogurt and soy milk and mix into a soft, slightly tacky dough.",
      "Knead for 4 to 5 minutes until smooth, then cover and rest for at least 30 minutes.",
      "Divide into equal balls. Roll one ball at a time into an oval roughly 5 mm thick, keeping the others covered.",
      "Heat a heavy dry frying pan until very hot. Cook each naan until large bubbles form and the underside has dark spots, then flip and cook the second side.",
      "Brush immediately with garlic butter, scatter with chopped coriander and keep warm under a clean towel while the remaining naan cook.",
    ],
  },
  "rajma-recipe": {
    whyItWorks: "Rajma becomes rich when kidney beans simmer in the masala long enough for their starch to thicken it. Mashing a small portion gives body, while slow cooking after the tomato stage allows the beans and gravy to taste integrated rather than separate.",
    cues: ["Dried kidney beans must be fully tender before they enter the masala.", "The tomato base should be thick and brick-red with no raw aroma.", "A finished rajma gravy should coat the back of a spoon."],
    substitutions: ["Tinned kidney beans are convenient; rinse them and reduce the initial simmering time.", "Black cardamom adds smokiness but can be omitted if unavailable.", "Use a little amchur instead of lemon for final acidity."],
    leftovers: "Rajma improves overnight. Refrigerate for up to three days and loosen gradually while reheating; boil until piping hot before serving.",
  },
  "palak-tofu-recipe": {
    whyItWorks: "Briefly cooking the spinach preserves its colour, and browning tofu separately stops it crumbling into the sauce. The spinach purée is simmered gently after blending so it stays fresh rather than becoming dark and metallic.",
    cues: ["Stop cooking spinach as soon as it has fully wilted.", "Drain excess water before blending or the gravy will be thin.", "Fold browned tofu into the finished sauce and simmer only long enough to warm through."],
    substitutions: ["Frozen leaf spinach works if thawed and squeezed well.", "A spoonful of cashew cream softens bitterness without dairy.", "Extra-firm tofu can be pan-fried or baked before adding."],
    leftovers: "Refrigerate for up to two days. Reheat gently and avoid prolonged boiling, which dulls the colour and can toughen the tofu.",
    instructions: [
      "Pat the tofu dry, cut into cubes and brown in a lightly oiled pan. Transfer to a plate.",
      "Add the spinach, green chillies and cashews to the pan and cook only until the spinach wilts. Cool briefly, then blend until smooth.",
      "Heat the remaining oil and cook any whole spices until fragrant. Add the onion and cook until soft and lightly golden.",
      "Stir in the garlic and cook for 30 seconds. Add the tomato and cook until soft, thick and jammy.",
      "Add the garam masala and cook briefly, then pour in the spinach purée with enough water to reach a thick sauce consistency.",
      "Simmer gently for 3 to 4 minutes. Fold in the browned tofu and warm through for another 3 minutes.",
      "Crush in the dried fenugreek leaves, add optional oat cream and adjust the salt before serving.",
    ],
  },
  "chickpea-curry-recipe": {
    whyItWorks: "This everyday chickpea curry is deliberately saucier than chana masala. Thoroughly cooking the onion, garlic and tomato base builds depth, while a final simmer lets chickpeas absorb seasoning and gives the gravy a cohesive texture.",
    cues: ["Onions should be soft and golden with no pale raw pieces.", "Spices need only a short fry; add tomato immediately if they threaten to catch.", "Taste a chickpea, not just the sauce, when checking the final salt."],
    substitutions: ["Cooked dried chickpeas bring a firmer texture than tinned.", "Coconut milk can replace part of the water for a richer variation.", "Spinach may be folded in for the final few minutes."],
    leftovers: "Refrigerate for three days or freeze for up to three months. Thaw fully and add water as needed while reheating.",
    instructions: [
      "Grind the fennel, fenugreek, cardamom seeds and cinnamon into a fine spice mixture and set aside.",
      "Heat the oil in a sauté pan and add the cumin seeds. When they sizzle, add the onion, curry leaves and garlic.",
      "Cook until the onion is soft and golden, then add the tomatoes, paprika, cayenne, turmeric and ground spice mixture.",
      "Cook over medium heat, stirring frequently, until the tomatoes darken and most of their liquid has evaporated.",
      "Add the drained chickpeas, salt and water. Bring to a simmer and cook for 10 minutes so the chickpeas absorb the masala.",
      "Stir in the coconut milk and warm gently without boiling hard. Taste for salt, garnish with fresh coriander and serve.",
    ],
  },
  "aloo-baingan-recipe": {
    whyItWorks: "Potato and aubergine cook at different rates, so the potato starts first and the aubergine follows once the pan is hot. Using a wide pan allows moisture to escape, concentrating the masala instead of steaming both vegetables into softness.",
    cues: ["Cut potato smaller than aubergine so both finish together.", "Aubergine should brown at the edges before the pan is covered.", "Stir with a folding motion to keep the tender pieces intact."],
    substitutions: ["Small firm aubergines hold their shape especially well.", "Tinned tomato can replace fresh, but cook it until no watery liquid remains.", "Amchur or lemon can supply the final tang."],
    leftovers: "Store for up to three days. Reheat in a wide pan without excessive stirring; the aubergine becomes more delicate after chilling.",
    instructions: [
      "Cut the potatoes into small even wedges and the aubergine into slightly larger pieces. Keep the potato in cold water until needed.",
      "Heat the oil in a wide pan. Add the cumin seeds, then the onion and green chilli, and cook until lightly golden.",
      "Add the garlic and cook for 30 seconds. Drain the potato, add it to the pan and stir-fry for 3 minutes.",
      "Cover and cook until the potato begins to soften, then add the aubergine and fry uncovered until its edges start to colour.",
      "Add the salt, turmeric, red chilli, garam masala and ground coriander. Fold gently to coat the vegetables.",
      "Add the tomatoes and a small splash of water. Cover and cook until the potato is tender and the aubergine is soft but still holding its shape.",
      "Uncover and simmer away excess liquid. Garnish with fresh coriander and serve.",
    ],
  },
  "mushroom-masala-recipe-punjabi-mushroom-curry": {
    whyItWorks: "Mushrooms release a surprising amount of water. Browning them in a roomy pan before combining with the masala prevents a thin grey sauce and develops savoury flavour that stands up to the tomato and spices.",
    cues: ["Do not crowd the pan; mushrooms should sizzle rather than boil in their liquid.", "Wait for released moisture to evaporate before judging the colour.", "The final gravy should be glossy and thick enough to sit on the mushrooms."],
    substitutions: ["Chestnut mushrooms have more flavour, but ordinary button mushrooms work.", "Cashew cream can soften the sauce without masking the mushrooms.", "Peas may be added near the end for sweetness and colour."],
    leftovers: "Refrigerate for up to two days and reheat until piping hot. Add water sparingly because mushrooms release more liquid as they warm.",
    instructions: [
      "Blend the onion, ginger and garlic into a smooth paste. Keep the tomato purée separate.",
      "Heat the oil in a wide pan. Add the cumin, bay leaf, cinnamon, cardamom and cloves and cook until fragrant.",
      "Add the onion paste and cook, stirring regularly, until golden, reduced and no longer raw-smelling.",
      "Add the tomato purée and cook until the masala is thick, darker and showing a little oil at the edges.",
      "Stir in the turmeric, chilli powder and ground coriander, then add the mushrooms.",
      "Cook uncovered until the mushrooms release their liquid and most of it evaporates.",
      "Add the water and salt and simmer until the mushrooms are tender and the gravy coats them.",
      "Finish with garam masala, crushed dried fenugreek and fresh coriander.",
    ],
  },
  "instant-pot-chana-masala": {
    whyItWorks: "Pressure cooking is most useful when it tenderises chickpeas while drawing the masala into them. Deglazing the pot thoroughly avoids a burn warning, and an uncovered reduction after pressure release corrects any excess liquid.",
    cues: ["Scrape every browned patch from the base after adding tomato or water.", "Cooked chickpeas should crush easily between finger and thumb.", "Use sauté mode after pressure cooking until the sauce coats rather than floods the chickpeas."],
    substitutions: ["For tinned chickpeas, shorten pressure time and use less liquid.", "Natural pressure release gives dried chickpeas a more even texture.", "Add lemon and fresh coriander only after pressure cooking."],
    leftovers: "Cool and refrigerate for three days. The sauce thickens overnight, so add a small splash of water before reheating on sauté mode or the hob.",
    instructions: [
      "Set the Instant Pot to sauté and heat the oil. Add the cumin, ajwain, bay leaf, cinnamon, cardamom and cloves.",
      "When fragrant, add the onion and cook until soft and golden. Add the ginger, garlic and green chillies and cook for 30 seconds.",
      "Add the tomatoes and cook until pulpy and reduced, then stir in the turmeric and chilli powder.",
      "Add the chickpeas, salt and water. Scrape the base thoroughly so no browned masala remains stuck to the pot.",
      "Seal and cook on high pressure. For cooked or tinned chickpeas use 5 minutes; for soaked dried chickpeas use about 30 minutes.",
      "Allow a natural pressure release for at least 12 minutes before opening.",
      "Return to sauté mode. Mash a small spoonful of chickpeas and simmer until the sauce reaches the desired thickness.",
      "Stir in the garam masala and lemon juice, then garnish with fresh coriander.",
    ],
  },
  "vegan-cauliflower-tikka-masala": {
    whyItWorks: "Roasting the cauliflower separately concentrates its flavour and prevents the florets watering down the tikka masala sauce. A well-reduced tomato base provides structure, and the roasted cauliflower is folded in late to retain browned edges.",
    cues: ["Dry cauliflower thoroughly so the marinade adheres.", "Roast with space between florets until the tips are dark and the stems are tender.", "The sauce is ready before combining when it looks smooth, glossy and no longer tastes sharply of tomato."],
    substitutions: ["Broccoli can replace some cauliflower but cooks more quickly.", "Soy yogurt or thick oat yogurt works in the marinade.", "Cashew cream can replace commercial vegan cream."],
    leftovers: "Refrigerate for up to three days. Reheat uncovered when possible so the cauliflower does not become overly soft.",
  },
  "dosa-recipe": {
    whyItWorks: "Dosa batter relies on fermentation for flavour, browning and a lacy texture. The pan must be evenly hot but not smoking, and spreading from the centre with light pressure creates a thin crepe without tearing the setting batter.",
    cues: ["Fermented batter should smell pleasantly tangy and show tiny bubbles.", "A drop of water should skitter and evaporate on the pan, not vanish instantly in smoke.", "The dosa releases naturally when the underside is crisp and golden."],
    substitutions: ["Short-grain rice is preferable to aromatic basmati for traditional texture.", "A small amount of cooked rice can help crispness if your batter remains soft.", "Fermentation time varies greatly with room temperature; judge the batter, not only the clock."],
    leftovers: "Fermented batter keeps refrigerated for up to three days and becomes tangier. Cooked dosa soften quickly and are best eaten straight from the pan.",
  },
  "coconut-chutney-recipe": {
    whyItWorks: "Fresh coconut supplies body while roasted gram or nuts keep the chutney creamy rather than watery. The hot tempering is poured over at the end, carrying mustard, chilli and curry-leaf aroma across the cool chutney.",
    cues: ["Add water gradually while blending; the chutney should be spoonable, not runny.", "Mustard seeds should pop before curry leaves enter the hot oil.", "Stand back when adding curry leaves because their moisture makes the oil spit."],
    substitutions: ["Unsweetened frozen coconut is the closest substitute for fresh.", "Roasted peanuts give a stronger flavour than roasted gram.", "Use lime or lemon only in small amounts so acidity does not dominate."],
    leftovers: "Refrigerate immediately and use within two days. Stir in a spoonful of water if it thickens, but discard it if the aroma becomes sour or fermented.",
  },
  "jeera-rice-recipe": {
    whyItWorks: "Rinsing removes loose starch and soaking helps basmati elongate without breaking. Blooming cumin in fat before the rice is added distributes its nutty aroma, while a covered rest finishes the grains without additional water.",
    cues: ["Rinse until the water changes from milky to nearly clear.", "Cumin should darken slightly and smell toasted, never blacken.", "After cooking, rest covered before fluffing gently with a fork."],
    substitutions: ["Brown basmati needs more water and a longer cooking time.", "Neutral oil works in place of vegan butter.", "A bay leaf or small cinnamon piece is optional; too many whole spices overwhelm the cumin."],
    leftovers: "Cool cooked rice quickly, refrigerate within one hour and consume within one day. Reheat once until steaming hot throughout.",
  },
  "vegetable-pakora": {
    whyItWorks: "A thick gram-flour coating protects the vegetables while irregular edges become crisp. The vegetables contribute moisture, so the batter should rest briefly before you decide whether any extra water is necessary.",
    cues: ["Cut vegetables thinly and evenly so they cook in the same time as the batter.", "The mixture should hold together on a spoon without dripping.", "Maintain steady bubbling and fry in small batches to avoid greasy pakoras."],
    substitutions: ["Use a mixture of onion, potato, cauliflower and spinach, avoiding very watery vegetables.", "Rice flour can replace a small portion of gram flour for extra crunch.", "Adjust chilli independently from the aromatic spices."],
    leftovers: "Pakoras are best immediately. Refrigerate for up to two days and reheat in a hot oven or air fryer until crisp and piping hot.",
    instructions: [
      "Combine the gram flour, cumin seeds, garam masala, turmeric and salt in a large bowl.",
      "Add the thinly sliced potato and onion, spinach and small cauliflower pieces. Toss until evenly dusted with the seasoned flour.",
      "Rest for 10 minutes so the salted vegetables release some moisture, then mix again.",
      "Add water one tablespoon at a time only until a thick coating clings to the vegetables.",
      "Heat enough neutral oil for deep-frying to about 175°C.",
      "Lower small, loose spoonfuls into the oil and fry in batches for 5 to 7 minutes, turning as needed, until crisp and golden throughout.",
      "Drain on kitchen paper, season lightly and serve immediately.",
    ],
  },
};

export function getRecipeDepth(slug: string) {
  return recipeDepth[slug];
}
