const CURRY_HUB_RECIPE_SLUGS = new Set([
  "chana-masala",
  "chickpea-curry-recipe",
  "easy-vegan-indian-butter-chickpeas",
  "instant-pot-chana-masala",
  "instant-pot-chickpea-coconut-curry",
  "kala-chana-recipe",
  "palak-chole",
  "sweet-potato-chickpea-spinach-curry",
  "coconut-dal-with-kidney-beans",
  "indian-red-lentil-dahl",
  "pressure-cooker-indian-moong-dal",
  "slow-cooker-dal",
  "spicy-lentil-bean-stew",
  "madra-recipe-himachali-rajma-madra-recipe",
  "rajma-recipe",
  "vegan-blackeye-bean-curry",
  "easy-butter-bean-curry",
  "saag-butter-beans",
  "aloo-baingan-recipe",
  "aloo-methi-potato-and-fenugreek-leaves-curry",
  "aloo-muttar",
  "aloo-tofu-recipe",
  "bengali-phulkopir-aloo-dalna",
  "bombay-aloo",
  "dum-aloo-recipe-mughlai-style",
  "jeera-aloo",
  "kashmiri-dum-aloo",
  "saag-aloo",
  "creamy-tofu-korma-curry",
  "dum-tofu-recipe",
  "kashmiri-lal-tofu-tofu-in-kashmiri-chili-tomato-curry-sauce",
  "madras-curry-tofu-casserole",
  "matar-tofu-recipe",
  "palak-tofu-recipe",
  "paneer-tikka-masala-recipe-restaurant-style",
  "tofu-butter-masala-recipe",
  "tofu-kondattam-south-indian-spicy-crispy-tofu",
  "tofu-pasanda-tofu-with-velvety-pepita-poppy-seed-sauce",
  "eggplant-curry-south-indian-brinjal-curry",
  "gobi-65-recipe-cauliflower-65-fry",
  "indian-style-cauliflower",
  "mushroom-masala-recipe-punjabi-mushroom-curry",
  "mushroom-matar-masala-mushroom-pea-curry",
  "oriya-ghanta-tarkari",
  "tandoori-gobi-gobi-tikka-tandoori-cauliflower",
  "vegan-cauliflower-tikka-masala",
  "veg-kurma-recipe-hotel-style-vegetable-korma",
  "veg-makhanwala",
  "vegetable-bhuna-north-indian-vegetable-curry",
  "vegetable-vindaloo",
  "restaurant-style-vegan-malai-kofta",
]);

export function isCurryHubRecipe(slug: string) {
  return CURRY_HUB_RECIPE_SLUGS.has(slug);
}

export { CURRY_HUB_RECIPE_SLUGS };